allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
