// AUTO-GENERATED by scripts/generate-email-theme.ts — do not edit by hand.
// Source of truth: app/styles/tailwind.css. Run `pnpm email:theme` to refresh.
//
// Email-safe (sRGB hex) projection of the OKLCH design tokens, because email
// clients support neither oklch(), CSS variables, nor Tailwind classes. A drift
// test (email-theme.test.ts) fails CI if this no longer matches the CSS.

export const emailColors = {
	background: '#ffffff',
	foreground: '#020817',
	card: '#ffffff',
	cardForeground: '#020817',
	muted: '#e6edf4',
	mutedForeground: '#404a59',
	primary: '#009977',
	primaryForeground: '#f8fafc',
	border: '#e2e8f0',
} as const

export const emailRadius = '8px'

export const emailFont =
	"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"

export const emailText = {
	h3: { fontSize: '32px', lineHeight: '36px' },
	h5: { fontSize: '24px', lineHeight: '32px' },
	bodySm: { fontSize: '16px', lineHeight: '20px' },
	bodyXs: { fontSize: '14px', lineHeight: '18px' },
	body2xs: { fontSize: '12px', lineHeight: '16px' },
} as const
