/**
 * Generates `app/components/emails/email-theme.generated.ts` — the email-safe
 * (sRGB hex) projection of the design tokens.
 *
 * The design system's source of truth is `app/styles/tailwind.css`, where the
 * tokens are OKLCH custom properties consumed by Tailwind. Email clients
 * (Outlook's Word engine, older Gmail, …) support none of that — no external
 * CSS, no CSS variables, no Tailwind classes, no `oklch()`. So emails must ship
 * inline `sRGB` hex. Rather than hand-copy values (which would drift), we derive
 * them here and a unit test (`email-theme.test.ts`) fails CI if the committed
 * file no longer matches the CSS. One source of truth, mechanically projected.
 *
 * Run with `pnpm email:theme`.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const CSS_PATH = join(ROOT, 'app/styles/tailwind.css')
const OUT_PATH = join(ROOT, 'app/components/emails/email-theme.generated.ts')

/** Colours emails actually use, mapped from CSS var name → export key. */
const COLOR_TOKENS: Array<[cssVar: string, key: string]> = [
	['background', 'background'],
	['foreground', 'foreground'],
	['card', 'card'],
	['card-foreground', 'cardForeground'],
	['muted', 'muted'],
	['muted-foreground', 'mutedForeground'],
	['primary', 'primary'],
	['primary-foreground', 'primaryForeground'],
	['border', 'border'],
]

/** Type-scale steps emails use, mapped from CSS `--text-*` name → export key. */
const TEXT_TOKENS: Array<[cssName: string, key: string]> = [
	['h3', 'h3'],
	['h5', 'h5'],
	['body-sm', 'bodySm'],
	['body-xs', 'bodyXs'],
	['body-2xs', 'body2xs'],
]

/**
 * The repo defines no font token — it relies on Tailwind's default `font-sans`
 * (a `system-ui` stack). This is the email-safe equivalent of that same stack
 * (older clients don't understand `system-ui`/`ui-sans-serif`), so it is the
 * projection of an existing decision, not a competing source of truth.
 */
const EMAIL_FONT_STACK =
	"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"

const REM_PX = 16

function remToPx(rem: string): number {
	return Math.round(parseFloat(rem) * REM_PX)
}

/** Extract the body of a top-level `selector { … }` block from the CSS. */
function block(css: string, selector: string): string {
	const start = css.indexOf(selector)
	if (start === -1) throw new Error(`Selector ${selector} not found in CSS`)
	const open = css.indexOf('{', start)
	const close = css.indexOf('}', open)
	return css.slice(open + 1, close)
}

function readVar(blockBody: string, name: string): string {
	const match = blockBody.match(new RegExp(`--${name}\\s*:\\s*([^;]+);`))
	if (!match?.[1]) throw new Error(`--${name} not found`)
	return match[1].trim()
}

// --- OKLCH → sRGB hex (CSS Color 4 / Björn Ottosson's reference formulae) ---

function parseOklch(value: string): { L: number; C: number; h: number } {
	const m = value.match(/oklch\(\s*([\d.]+)%\s+([\d.]+)\s+([\d.]+)\s*\)/)
	if (!m?.[1] || !m[2] || !m[3]) throw new Error(`Cannot parse OKLCH: ${value}`)
	return { L: parseFloat(m[1]) / 100, C: parseFloat(m[2]), h: parseFloat(m[3]) }
}

function gammaEncode(c: number): number {
	const v = c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055
	return Math.min(1, Math.max(0, v))
}

function oklchToHex(value: string): string {
	const { L, C, h } = parseOklch(value)
	const hr = (h * Math.PI) / 180
	const a = C * Math.cos(hr)
	const b = C * Math.sin(hr)

	const l_ = L + 0.3963377774 * a + 0.2158037573 * b
	const m_ = L - 0.1055613458 * a - 0.0638541728 * b
	const s_ = L - 0.0894841775 * a - 1.291485548 * b
	const l = l_ ** 3
	const m = m_ ** 3
	const s = s_ ** 3

	const r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
	const g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
	const bl = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s

	const toHex = (x: number) =>
		Math.round(gammaEncode(x) * 255)
			.toString(16)
			.padStart(2, '0')
	return `#${toHex(r)}${toHex(g)}${toHex(bl)}`
}

/** Build the full contents of the generated module (pure — used by the test). */
export function buildEmailThemeModule(css: string): string {
	const root = block(css, ':root')
	const theme = block(css, '@theme {')

	const colors = COLOR_TOKENS.map(
		([cssVar, key]) => `\t${key}: '${oklchToHex(readVar(root, cssVar))}',`,
	).join('\n')

	const radiusPx = remToPx(readVar(root, 'radius'))

	const text = TEXT_TOKENS.map(([cssName, key]) => {
		const size = remToPx(readVar(theme, `text-${cssName}`))
		const lineHeight = remToPx(readVar(theme, `text-${cssName}--line-height`))
		return `\t${key}: { fontSize: '${size}px', lineHeight: '${lineHeight}px' },`
	}).join('\n')

	return `// AUTO-GENERATED by scripts/generate-email-theme.ts — do not edit by hand.
// Source of truth: app/styles/tailwind.css. Run \`pnpm email:theme\` to refresh.
//
// Email-safe (sRGB hex) projection of the OKLCH design tokens, because email
// clients support neither oklch(), CSS variables, nor Tailwind classes. A drift
// test (email-theme.test.ts) fails CI if this no longer matches the CSS.

export const emailColors = {
${colors}
} as const

export const emailRadius = '${radiusPx}px'

export const emailFont =
	"${EMAIL_FONT_STACK}"

export const emailText = {
${text}
} as const
`
}

async function main() {
	const css = await readFile(CSS_PATH, 'utf8')
	await writeFile(OUT_PATH, buildEmailThemeModule(css), 'utf8')
	console.log(`✓ wrote ${OUT_PATH.replace(ROOT + '/', '')}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	await main()
}
